[package]
name = "webcat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
webcat_script = { path = "../webcat_script" }

[dev-dependencies]
tux = { path = "../tux" }
